### ISSUE TITLE
给动手能力赞一个，不知道做到那部分了

### ISSUE THREAD

**Issue by dubuqingfeng** [mindcont/RubikRobot#1]

**Comment by mindcont** [comment]
很荣幸能够得到你的回复，
目前进行到蓝牙发送数据和提高识别效率这两部分工作，硬件部分基本完成，已实现通过串口向STM32发送数据，驱动舵机进行对应的旋转。

**Comment by dubuqingfeng** [comment]
嗯，提高识别效率主要在opencv的那块了，蓝牙也有很多开源实现，很重要一部分是硬件部分，硬件搭好是解决好魔方的还原的重要一部分，一开始第一版的成本较便宜，单说物料大概几百左右，第二版的就贵了，网上都放了测试视频，有兴趣的完了说下。还有一点是驱动舵机的时候，有时候是需要两个同时一起转的，另外我们那是八个舵机，具体的占空比的设计需要仔细去考虑，在STM32调控方面需要做好这部分，我相信这块你比我要熟。

**Comment by mindcont** [comment]
我刚接触android不久，目前还在研读你的代码，增加注释，并尝试着进行有效的修改，
希望大神多多关照、提携！
