### ISSUE TITLE
抄原子的代码

### ISSUE THREAD

**Issue by PaPazhao** [mindcont/RubikRobot#4]

**Comment by PaPazhao** [comment]
无耻

**Comment by mindcont** [comment]
@PaPazhao

首先很高兴兄台，能关注这个项目并给出批评。我还是很高兴的，毕竟无人问津😁

其次这只是一个在学校比赛的小项目，不必纠结许多。在国内嵌入式学习方面受原子哥和他的论坛，收益颇多，可能存在一部分代码直接拿来用了，时隔一年我也记不清那部分了，记得当时能跑通实属不易。关于代码原创我从没有这样描述今后也不会，一是没必要重复造轮子，二是水平和能力都还不够，我和我小组做的只是集成和调通吧。

当初把它开源出来的目的，也是想启发和我以前一样的电子系同学，提供一个好玩的思路，安卓+硬件+蓝牙诸如此类的例子，没有涉及商业利益，所以不必太纠结，经您提醒我会在致谢中添加原子哥的。

Cheers🤝😸💪~~
